# Generated by Django 3.0.7 on 2020-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_user', models.CharField(max_length=30, unique=True)),
                ('text', models.CharField(max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('json_format', models.CharField(max_length=3000)),
                ('ua', models.CharField(max_length=300)),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
