# Generated by Django 2.0.5 on 2020-07-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0003_cookies_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='pwd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
